pool: nav-prod
config:
  cleanupPolicy: delete
  minimumInSyncReplicas: 1
  partitions: 1
  replication: 3
  retentionBytes: -1
  retentionHours: 720
acl:
  - team: k9saksbehandling
    application: k9-klage
    access: read
  - team: supstonad
    application: su-se-bakover
    access: read
  - team: teamforeldrepenger
    application: fpsak
    access: read
  - team: teamfamilie
    application: familie-klage
    access: read
  - team: klage
    application: klage-kafka-manager
    access: read
