apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: internal-events.v1
  namespace: klage
  labels:
    team: klage
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
    {{key}}: {{value}}
  {{/each}}
  acl:
    - team: klage
      application: kabal-api
      access: readwrite
  {{#each acl}}
    - team: {{team}}
      application: {{application}}
      access: {{access}}
  {{/each}}
